name: Deploy Notify Service

on:
  push:
    branches: [ develop, master, sales ]  # Trigger for three branches

env:
  SERVICE_NAME: notify
  REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/develop' && 'staging' || github.ref == 'refs/heads/sales' && 'sales' || 'production' }}
    permissions:
      contents: read
      packages: write
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Set up SSH Agent to deploy to respective environments
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ github.ref == 'refs/heads/develop' && secrets.STAGING_SSH_PRIVATE_KEY || github.ref == 'refs/heads/sales' && secrets.SALES_SSH_PRIVATE_KEY || secrets.PROD_SSH_PRIVATE_KEY }}

      # Deploy to the appropriate server
      - name: Deploy to Server
        env:
          DEPLOY_ENV: ${{ github.ref == 'refs/heads/develop' && 'staging' || github.ref == 'refs/heads/sales' && 'sales' || 'production' }}
        run: |
          # SSH into the right host and deploy the Docker image
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ github.ref == 'refs/heads/develop' && secrets.STAGING_HOST || github.ref == 'refs/heads/sales' && secrets.SALES_HOST || secrets.PROD_HOST }} << 'EOF'
            # Navigate to the corresponding directory
            cd /root/${{ env.DEPLOY_ENV }}

            # Pull the updated image from GitHub registry
            docker compose pull ${{ env.SERVICE_NAME }}

            # Recreate and restart the container
            docker compose up -d ${{ env.SERVICE_NAME }}
          EOF

      # Print debug info
      - name: Print debug info
        run: |
          echo "Deploying to environment: ${{ env.DEPLOY_ENV }}"
          echo "Using host: ${{ github.ref == 'refs/heads/develop' && secrets.STAGING_HOST || github.ref == 'refs/heads/sales' && secrets.SALES_HOST || secrets.PROD_HOST }}"
          echo "Using SSH username: ${{ secrets.SSH_USERNAME }}"
